### ISSUE TITLE
Add overload for MakeMenuButton that takes Func<UIMenu>

### ISSUE THREAD

**Issue by Leo506** [ArbusBiz/Arbus.Mobile.Essentials#19]
Now if we pass `UIMenu `instance in `MakeMenuButton` with `UIAction ` that depends on external resource (e.g. DataContext) and this resource will be null on creating moment we will get `NullReferenceException`. As workaround we can use `MakeMenuButton `without parameter and `AddAction `method (where we set button menu). It is not obviously. So I sufggest use `Func<UIMenu>` instead of `UIMenu `instance

**Comment by evgenyvalavin** [comment]
Don't forget Arbus.Mobile.Essentials is a GitHub Public Project while proposing changes. Not everyone has a property DataContext or MakeMenuButton(UIMenu menu) doesn't work for them.

**Comment by Leo506** [comment]
Ok. Instead of replacing we can add overload that takes `Func<UIMenu>`

**Comment by evgenyvalavin** [comment]
Sounds like a proposal!
