### ISSUE TITLE
Add UIButtonConfiguration.SetTitlePadding() and .SetImagePadding()

### ISSUE THREAD

**Issue by Leo506** [ArbusBiz/Arbus.Mobile.Essentials#30]
If button contains icon and title then if you want set distance between its you need to use `UIButtonConfiguration.ImagePadding` or `UIButtonConfiguration.TitlePadding`
Here the explanation: [stackoverflow](https://stackoverflow.com/questions/68328038/imageedgeinsets-was-deprecated-in-ios-15-0)
So now we need new corresponding extension methods

**Comment by evgenyvalavin** [comment]
@Leo506 you're welcome to contribute
